#!/bin/bash

# Copyright 2015 Andreas Wilhelm
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Script configuration.
FHEM_VERSION=5.6
FHEM_HOSTNAME=""
FHEM_USER_NAME=fhem
FHEM_USER_PASS=s3cr37
FHEM_ROOT_PASS=""

# Define the usage text.
USAGE=$( cat <<EOF
Usage: `basename $0` [-hv] [-V <fhem_version>] [-H <hostname>] [-u <username>] [-p <user_password>] [-r <root_password>]\n
-h|--help:
\tDisplays this help.
-v|--version
\tDisplays the current version of this script.
-V|--fhem-version
\tFhem version to be used.
-H|--hostname
\tThe hostname to be used.
-u|--username
\tName of the fhem user.
-p|--password
\tPassword of the fhem user.
-r|--root
\tPassword of the root user.
EOF
)

# All users with $UID 0 have root privileges.
ROOT_UID=0

# Just one single user is called root.
ROOT_NAME="root"

# Function for messages.
function info() {
  echo -e "$*" >&2
  exit 0
}

function warning() {
  echo -e "$*" >&2
}

function error() {
  echo -e "$*" >&2
  exit 1
}

# Check if user has root privileges.
if [[ $EUID -ne $ROOT_UID ]]; then
  error "This script must be run as root!"
fi

# Fetch command line options.
while [[ -n "${1+xxx}" ]]
do
  case "$1" in 
    --help|-h)
      info "$USAGE"
      ;;
    --version|-v)
      info "`basename $0` version 1.0"
      ;;
    -V|--fhem-version)
      shift
      FHEM_VERSION=$1

      if [[ ! "$FHEM_VERSION" ]]; then
        error "Missing fhem version code!\n\n$USAGE"
      fi

      FHEM_VERSION=$(tr '[:upper:]' '[:lower:]' <<< $FHEM_VERSION)

      shift
      ;;
    -H|-hostname)
      shift
      FHEM_HOSTNAME=$1

      if [[ ! "$FHEM_HOSTNAME" ]]; then 
        error "Missing hostname!\n\n$USAGE"
      fi

      FHEM_HOSTNAME=$(tr '[:upper:]' '[:lower:]' <<< $FHEM_HOSTNAME)

      shift
      ;;
    -u|--username)
      shift
      FHEM_USER_NAME=$1

      if [[ ! "$FHEM_USER_NAME" ]]; then
        error "Missing username!\n\n$USAGE"
      fi

      FHEM_USER_NAME=$(tr '[:upper:]' '[:lower:]' <<< $FHEM_USER_NAME)

      shift
      ;;
    -p|--password)
      shift
      FHEM_USER_PASS=$1

      if [[ ! "$FHEM_USER_PASS" ]]; then
        error "Missing user password!\n\n$USAGE"
      fi

      shift
      ;;
    -r|--root)
      shift
      FHEM_ROOT_PASS=$1

      if [[ ! "$FHEM_ROOT_PASS" ]]; then
        error "Missing root password!\n\n$USAGE"
      fi

      shift
      ;;
    -*)
      error "unrecognized option: $1\n\n$USAGE"
      ;;
    *)
      break
      ;;
  esac
done

# First of all change the root password.
if [ ! -z "$FHEM_ROOT_PASS" -a "$FHEM_ROOT_PASS" != " " ]; then
  echo $ROOT_NAME:$FHEM_ROOT_PASS | chpasswd
fi

# Change hostname of given.
if [ ! -z "$FHEM_HOSTNAME" -a "$FHEM_HOSTNAME" != " " ]; then
  # Fetch the current hostname ...
  CURRENT_HOSTNAME=`cat /etc/hostname | tr -d " \t\n\r"`

  # ... and change it within /etc/hostname ...
  echo $FHEM_HOSTNAME > /etc/hostname

  # ... and within /etc/hosts.
  sed -i "s/127.0.1.1.*$CURRENT_HOSTNAME/127.0.1.1\t$FHEM_HOSTNAME/g" /etc/hosts
fi

# Fetch the latest package information ...
apt-get -y update

# ... and run a system upgrade.
apt-get -y dist-upgrade

# Install required software packages.
apt-get -y install build-essential vim htop telnet wget curl w3m lynx screen unzip libdevice-serialport-perl libio-socket-ssl-perl libwww-perl

# Rebuild dkms for all installed kernel versions.
ls /var/lib/initramfs-tools | xargs -n1 /usr/lib/dkms/dkms_autoinstaller start 

# Remove outdated kernel(s) ...
dpkg -l linux-* | awk '/^ii/{ print $2}' | grep -v -e `uname -r | cut -f1,2 -d"-"` | grep -e [0-9] | grep -E "(image|headers)" | xargs apt-get -y purge

# ... and update grub.
update-grub

# Remove the desktop environment ...
apt-get -y remove task-desktop

# ... and delete all outdated packages.
apt-get -y autoremove

# Delete the old raspberry pi user.
userdel --remove-home pi

# Create a new fhem user ...
useradd -m -g users -G sudo -s /bin/bash fhem

# ... and set the default password.
echo $FHEM_USER_NAME:$FHEM_USER_PASS | chpasswd

# Download the latest fhem release, ...
wget www.fhem.de/fhem-${FHEM_VERSION}.tar.gz -O /tmp/fhem-${FHEM_VERSION}.tar.gz

# ... extract the downloaded archive, ...
tar xzvf /tmp/fhem-${FHEM_VERSION}.tar.gz -C /tmp

# ... switch into the downloaded folder, ...
cd /tmp/fhem-${FHEM_VERSION}

# ... and run the installation procedure.
make install

# Set proper access rights ...
chown -R fhem /opt/fhem

# ... and remove the downloaded archive.
rm -r /tmp/fhem-${FHEM_VERSION}.tar.gz /tmp/fhem-${FHEM_VERSION}

# Create the fhem systemd service ...
echo "[Unit]
Description=FHEM Perl Server
After=syslog.target network.target

[Service]
User=fhem
Type=forking
WorkingDirectory=/opt/fhem
ExecStart=/opt/fhem/fhem.pl /opt/fhem/fhem.cfg
Restart=always

[Install]
WantedBy=multi-user.target" > /etc/systemd/system/fhem.service

# ... and for older systems the init.d service file.
cat > /etc/init.d/fhem <<EOF
#!/bin/sh

### BEGIN INIT INFO
# Provides:             fhem.pl
# Required-Start:       \$local_fs \$remote_fs
# Required-Stop:        \$local_fs \$remote_fs
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    FHEM server
### END INIT INFO

set -e
FHEM_PATH=/opt/fhem
FHEM_TELNET_PORT=7072

case "\$1" in
'start')
        echo "Starting fhem..."
        perl \$FHEM_PATH/fhem.pl \$FHEM_PATH/fhem.cfg
        RETVAL=\$?
        ;;
'stop')
        echo "Stopping fhem..."
        perl \$FHEM_PATH/fhem.pl \$FHEM_TELNET_PORT "shutdown"
        RETVAL=\$?
        ;;
'status')
        cnt=\`ps -ef | grep "fhem.pl" | grep -v grep | wc -l\`
        if [ "\$cnt" -eq "0" ] ; then
                echo "fhem is not running"
        else
                echo "fhem is running"
        fi
        ;;
*)
        echo "Usage: \$0 { start | stop | status }"
        RETVAL=1
        ;;
esac
exit \$RETVAL
EOF

# Finally start the fhem service.
su - $FHEM_USER_NAME -c "/etc/init.d/fhem start"
